package redhat.brms6workshop;

/**
 * This class was automatically generated by the data modeler tool.
 * $HASH(62823423391279a741bf881a33991615)
 */
@org.kie.api.definition.type.Label(value = "Violation Info")
public class Violation extends java.lang.Object implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    @org.kie.api.definition.type.Label(value = "Violation Code")
    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.String code;
    
    @org.kie.api.definition.type.Label(value = "Violation Description")
    @org.kie.api.definition.type.Position(value = 1)
    private java.lang.String description;

    public Violation() {
    }

    public Violation(java.lang.String code, java.lang.String description) {
        this.code = code;
        this.description = description;
    }


    
    public java.lang.String getCode() {
        return this.code;
    }

    public void setCode(java.lang.String code) {
        this.code = code;
    }
    
    public java.lang.String getDescription() {
        return this.description;
    }

    public void setDescription(java.lang.String description) {
        this.description = description;
    }
}