package redhat.brms6workshop.labs;

/**
 * This class was automatically generated by the data modeler tool.
 * $HASH(0112ed96b512740355812cf9711a20d3)
 */
@org.kie.api.definition.type.Label(value = "Application Event")
public class ApplicationEvent  implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    @org.kie.api.definition.type.Label(value = "Application ID")
    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.Integer applicationID;
    
    @org.kie.api.definition.type.Label(value = "Insured Name")
    @org.kie.api.definition.type.Position(value = 2)
    private java.lang.String insuredName;
    
    @org.kie.api.definition.type.Label(value = "Premium")
    @org.kie.api.definition.type.Position(value = 1)
    private java.lang.String premium;

    public ApplicationEvent() {
    }

    public ApplicationEvent(java.lang.Integer applicationID, java.lang.String premium, java.lang.String insuredName) {
        this.applicationID = applicationID;
        this.premium = premium;
        this.insuredName = insuredName;
    }


    
    public java.lang.Integer getApplicationID() {
        return this.applicationID;
    }

    public void setApplicationID(java.lang.Integer applicationID) {
        this.applicationID = applicationID;
    }
    
    public java.lang.String getInsuredName() {
        return this.insuredName;
    }

    public void setInsuredName(java.lang.String insuredName) {
        this.insuredName = insuredName;
    }
    
    public java.lang.String getPremium() {
        return this.premium;
    }

    public void setPremium(java.lang.String premium) {
        this.premium = premium;
    }
}