package redhat.brms6workshop.labs;

/**
 * This class was automatically generated by the data modeler tool.
 * $HASH(171a280973a8abe941e0c73785102f5a)
 */
@org.kie.api.definition.type.Label(value = "Driver Info")
public class Driver extends java.lang.Object implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    @org.kie.api.definition.type.Label(value = "Age")
    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.Integer age;
    
    @org.kie.api.definition.type.Label(value = "City")
    @org.kie.api.definition.type.Position(value = 1)
    private java.lang.String city;

    public Driver() {
    }

    public Driver(java.lang.Integer age, java.lang.String city) {
        this.age = age;
        this.city = city;
    }


    
    public java.lang.Integer getAge() {
        return this.age;
    }

    public void setAge(java.lang.Integer age) {
        this.age = age;
    }
    
    public java.lang.String getCity() {
        return this.city;
    }

    public void setCity(java.lang.String city) {
        this.city = city;
    }
}