package redhat.brms6workshop.labs;

/**
 * This class was automatically generated by the data modeler tool.
 * $HASH(9c6525f1d0134fac7118a8c84785babc)
 */
@org.kie.api.definition.type.Label(value = "Notification")
public class Notification  implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    @org.kie.api.definition.type.Label(value = "Agent Name")
    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.String agentName;
    
    @org.kie.api.definition.type.Label(value = "Customer Name")
    @org.kie.api.definition.type.Position(value = 2)
    private java.lang.String customerName;
    
    @org.kie.api.definition.type.Label(value = "Email ID")
    @org.kie.api.definition.type.Position(value = 1)
    private java.lang.String emailID;
    
    @org.kie.api.definition.type.Label(value = "Quote ID")
    @org.kie.api.definition.type.Position(value = 3)
    private java.lang.Integer quoteID;

    public Notification() {
    }

    public Notification(java.lang.String agentName, java.lang.String emailID, java.lang.String customerName, java.lang.Integer quoteID) {
        this.agentName = agentName;
        this.emailID = emailID;
        this.customerName = customerName;
        this.quoteID = quoteID;
    }


    
    public java.lang.String getAgentName() {
        return this.agentName;
    }

    public void setAgentName(java.lang.String agentName) {
        this.agentName = agentName;
    }
    
    public java.lang.String getCustomerName() {
        return this.customerName;
    }

    public void setCustomerName(java.lang.String customerName) {
        this.customerName = customerName;
    }
    
    public java.lang.String getEmailID() {
        return this.emailID;
    }

    public void setEmailID(java.lang.String emailID) {
        this.emailID = emailID;
    }
    
    public java.lang.Integer getQuoteID() {
        return this.quoteID;
    }

    public void setQuoteID(java.lang.Integer quoteID) {
        this.quoteID = quoteID;
    }
}