package redhat.brms6workshop.labs;

/**
 * This class was automatically generated by the data modeler tool.
 * $HASH(dba0d513a5d83544ece2b3677c60d817)
 */
@org.kie.api.definition.type.Label(value = "Premium")
public class Premium  implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    @org.kie.api.definition.type.Label(value = "Amount")
    @org.kie.api.definition.type.Position(value = 0)
    private java.math.BigDecimal amount;

    public Premium() {
    }

    public Premium(java.math.BigDecimal amount) {
        this.amount = amount;
    }


    
    public java.math.BigDecimal getAmount() {
        return this.amount;
    }

    public void setAmount(java.math.BigDecimal amount) {
        this.amount = amount;
    }
}