package redhat.brms6workshop.labs;

/**
 * This class was automatically generated by the data modeler tool.
 * $HASH(2eea8a1b0e8eefd9418613be730d6aed)
 */
@org.kie.api.definition.type.Label(value = "Quote")
public class Quote  implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Quote() {
    }




}