package redhat.brms6workshop.labs;

/**
 * This class was automatically generated by the data modeler tool.
 * $HASH(4930016a06e6bfe15793082930967a45)
 */
@org.kie.api.definition.type.Label(value = "Quote Event")
@org.kie.api.definition.type.Role(value = org.kie.api.definition.type.Role.Type.EVENT)
public class QuoteEvent  implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    @org.kie.api.definition.type.Label(value = "Insured Name")
    @org.kie.api.definition.type.Position(value = 3)
    private java.lang.String insuredName;
    
    @org.kie.api.definition.type.Label(value = "Premium")
    @org.kie.api.definition.type.Position(value = 2)
    private java.math.BigDecimal premium;
    
    @org.kie.api.definition.type.Label(value = "Quote Date")
    @org.kie.api.definition.type.Position(value = 0)
    private java.util.Date quoteDate;
    
    @org.kie.api.definition.type.Label(value = "Quote ID")
    @org.kie.api.definition.type.Position(value = 1)
    private java.lang.Integer quoteID;

    public QuoteEvent() {
    }

    public QuoteEvent(java.util.Date quoteDate, java.lang.Integer quoteID, java.math.BigDecimal premium, java.lang.String insuredName) {
        this.quoteDate = quoteDate;
        this.quoteID = quoteID;
        this.premium = premium;
        this.insuredName = insuredName;
    }


    
    public java.lang.String getInsuredName() {
        return this.insuredName;
    }

    public void setInsuredName(java.lang.String insuredName) {
        this.insuredName = insuredName;
    }
    
    public java.math.BigDecimal getPremium() {
        return this.premium;
    }

    public void setPremium(java.math.BigDecimal premium) {
        this.premium = premium;
    }
    
    public java.util.Date getQuoteDate() {
        return this.quoteDate;
    }

    public void setQuoteDate(java.util.Date quoteDate) {
        this.quoteDate = quoteDate;
    }
    
    public java.lang.Integer getQuoteID() {
        return this.quoteID;
    }

    public void setQuoteID(java.lang.Integer quoteID) {
        this.quoteID = quoteID;
    }
}