package redhat.brms6workshop.labs;

/**
 * This class was automatically generated by the data modeler tool.
 * $HASH(ee2c52b21dab54c19e522cba052817fe)
 */
@org.kie.api.definition.type.Label(value = "Vehicle")
public class Vehicle  implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    @org.kie.api.definition.type.Label(value = "Make")
    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.String make;

    public Vehicle() {
    }

    public Vehicle(java.lang.String make) {
        this.make = make;
    }


    
    public java.lang.String getMake() {
        return this.make;
    }

    public void setMake(java.lang.String make) {
        this.make = make;
    }
}