package redhat.brms6workshop.labs;

/**
 * This class was automatically generated by the data modeler tool.
 * $HASH(d950d56859ee7cebd3fdc576d3dbffee)
 */
@org.kie.api.definition.type.Label(value = "Violation Info")
public class Violation  implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Violation() {
    }




}